name: app_2_messages_ai
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  auth0_flutter: ^1.9.0
  flutter:
    sdk: flutter
  flutter_appauth: ^9.0.0
  flutter_secure_storage: ^8.0.0
  http: ^1.3.0
  provider: ^6.1.2
  universal_html: ^2.2.4
  url_launcher: ^6.3.1
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
